export const quotes = [
  "It ain't about how hard you hit. It's about how hard you can get hit and keep moving forward. — Rocky Balboa",
  "Suffering is the true test of life. — David Goggins",
  "The impediment to action advances action. What stands in the way becomes the way. — Marcus Aurelius",
  "Victory belongs to the most persevering. — Napoleon Bonaparte",
  "Discipline equals freedom. — Jocko Willink",
  "You are in danger of living a life so comfortable that you forget what you're capable of. — David Goggins",
  "He who has a why can endure almost any how. — Friedrich Nietzsche",
  "Sweat more in training. Bleed less in battle.",
  "The mind is the primary weapon. — Miyamoto Musashi",
  "Difficulties strengthen the mind, as labor does the body. — Seneca",

  "Conquer yourself, and you conquer the enemy.",
  "The pain you feel today will be the strength you feel tomorrow.",
  "A champion is someone who gets up when they can't. — Jack Dempsey",
  "Cowards die many times before their deaths; the valiant taste of death but once. — Shakespeare",
  "The body will quit a thousand times before the mind does.",
  "You don't rise to the occasion. You fall to the level of your preparation.",
  "Victory loves preparation.",
  "Hard times don't break strong men. They reveal them.",
  "What we do in life echoes in eternity.",
  "You become dangerous when you learn how to control your mind.",

  "Endure, and you will conquer.",
  "The fight is won or lost far away from witnesses. — Muhammad Ali",
  "Pain is temporary. Quitting lasts forever.",
  "Do not pray for an easy life. Pray for the strength to endure a hard one. — Bruce Lee",
  "Greatness is forged in solitude.",
  "Comfort is the enemy of progress.",
  "If you can suffer longer than the other man, you win. — Emil Zatopek",
  "The strongest steel is forged in the hottest fire.",
  "To dare is to lose one's footing momentarily. Not to dare is to lose oneself.",
  "A calm mind is a lethal weapon.",

  "You must understand that there is more than one path to the top of the mountain. — Miyamoto Musashi",
  "Think lightly of yourself and deeply of the world. — Miyamoto Musashi",
  "The ultimate aim of martial arts is not having to use them. — Miyamoto Musashi",
  "Perceive that which cannot be seen with the eye. — Miyamoto Musashi",

  "You have power over your mind — not outside events. Realize this, and you will find strength. — Marcus Aurelius",
  "If it is endurable, then endure it. Stop complaining. — Marcus Aurelius",
  "The best revenge is to be unlike him who performed the injury. — Marcus Aurelius",
  "What stands in the way becomes the way. — Marcus Aurelius",

  "A man who has committed a mistake and doesn’t correct it is committing another mistake. — Confucius",
  "Victory belongs to the most persevering. — Napoleon Bonaparte",
  "A soldier will fight long and hard for a bit of colored ribbon. — Napoleon Bonaparte",
  "Conquer yourself and you will conquer the battlefield.",

  "Discipline equals freedom. — Jocko Willink",
  "You don’t rise to the level of your expectations. You fall to the level of your training. — Jocko Willink",
  "Suffering is the true test of life. — David Goggins",
  "You are in danger of living a life so comfortable that you forget what you’re capable of. — David Goggins",
  "Suffering is the currency of greatness. — David Goggins",

  "If you know the enemy and know yourself, you need not fear the result of a hundred battles. — Sun Tzu",
  "Victorious warriors win first and then go to war. — Sun Tzu",
  "In the midst of chaos, there is also opportunity. — Sun Tzu",

  "It is not death that a man should fear, but never beginning to live. — Marcus Aurelius",
  "Cowards die many times before their deaths; the valiant taste of death but once.",
  "Sweat more in training. Bleed less in war.",
  "Comfort is the enemy of progress.",
  "Pressure is a privilege.",

  "If you can suffer longer than the other man, you win.",
  "The body will break before the mind does.",
  "Weakness leaves the body when the mind hardens.",
  "You do not negotiate with your excuses.",
  "When it is time to work, work. When it is time to rest, rest. — Zen proverb",
];
